export const styles = {
  page: { minHeight: "100vh", background: "#1C2622", color: "#EDE6D6", fontFamily: "'Work Sans', sans-serif", padding: "32px 20px 60px", maxWidth: 720, margin: "0 auto" },
  titleHeader: { marginBottom: 16, marginLeft: -20, marginRight: -20, marginTop: -32, padding: "18px 20px 14px", textAlign: "center", background: "linear-gradient(180deg, #263229 0%, #1C2622 100%)", borderBottom: "2px solid #C97A3D" },
  eyebrowRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 10, marginBottom: 6 },
  eyebrowRule: { width: 22, height: 1, background: "#C97A3D", opacity: 0.5 },
  eyebrow: { fontSize: 11, color: "#C97A3D" },
  h1: { fontFamily: "'Fraunces', serif", fontWeight: 700, fontSize: 22, color: "#FFFFFF", margin: 0 },
  crumbTrail: { marginTop: 0, marginBottom: 16, marginLeft: -20, marginRight: -20, display: "flex", flexDirection: "column", gap: 4, padding: "10px 8px", background: "#141C18", borderTop: "1px solid #2E3B34", borderBottom: "1px solid #2E3B34" },
  titleBlock: { marginBottom: 20 },
  overviewText: { fontSize: 14, lineHeight: 1.6, color: "#A9B3A9", margin: "10px 0 0" },
  crumbRow: { display: "flex", flexWrap: "wrap", alignItems: "baseline", gap: 6, paddingLeft: 4 },
  crumbPlain: { color: "#8B958B", fontSize: 13, margin: "6px 0 0" },
  crumbLink: { fontSize: 12, color: "#EDE6D6", opacity: 0.6, cursor: "pointer", transition: "opacity 0.15s" },
  crumbSep: { fontSize: 12, color: "#3F4C44" },
  crumbCountry: { fontFamily: "'Fraunces', serif", fontSize: 20, fontWeight: 700, color: "#FFFFFF" },
  foundedBadge: { display: "inline-block", fontSize: 11, padding: "5px 12px", borderRadius: 999, border: "1.5px solid", background: "#1C2622" },
  badgeRow: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  sectionGrid: { display: "flex", flexDirection: "column", gap: 12 },
  sectionCard: { background: "#232F29", border: "1.5px solid", borderRadius: 6, padding: "20px 18px", textAlign: "left", cursor: "pointer", color: "#EDE6D6", transition: "transform 0.15s" },
  sectionTag: { fontSize: 10, marginBottom: 8 },
  sectionName: { fontFamily: "'Fraunces', serif", fontSize: 22, fontWeight: 700, color: "#FFFFFF", marginBottom: 6 },
  sectionDesc: { fontSize: 13, color: "#A9B3A9", lineHeight: 1.5 },
  comingSoonBox: { border: "1.5px dashed", borderRadius: 6, padding: "40px 24px", textAlign: "center", marginTop: 8 },
  spiceListCount: { fontSize: 11, color: "#8B958B", fontFamily: "'Space Mono', monospace" },
  comingSoonDesc: { fontSize: 14, color: "#A9B3A9", lineHeight: 1.6, maxWidth: 420, margin: "0 auto" },
  regionGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  spiceLetterGrid: { display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 10 },
  regionCard: { background: "#232F29", border: "1.5px solid", borderRadius: 4, padding: "18px 16px", textAlign: "left", cursor: "pointer", color: "#EDE6D6", transition: "transform 0.15s" },
  spiceLetterCard: { background: "#232F29", border: "1.5px solid", borderRadius: 4, padding: "14px 8px", textAlign: "center", cursor: "pointer", color: "#EDE6D6", transition: "transform 0.15s", display: "flex", alignItems: "center", justifyContent: "center" },
  regionTag: { fontSize: 10, marginBottom: 8 },
  regionName: { fontFamily: "'Fraunces', serif", fontSize: 19, fontWeight: 600, marginBottom: 4 },
  regionCount: { fontSize: 12, color: "#8B958B" },
  groupCount: { fontSize: 11, color: "#8B958B", marginTop: 4, fontFamily: "'Work Sans', sans-serif" },
  countryGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  countryCard: { background: "#232F29", border: "1.5px dashed", borderRadius: 4, padding: "14px 14px", textAlign: "left", cursor: "pointer", color: "#EDE6D6", fontFamily: "'Fraunces', serif", fontSize: 16, transition: "transform 0.15s" },
  detail: { background: "#232F29", border: "1px solid #35443D", borderRadius: 6, padding: 24 },
  areaBox: { background: "#1C2622", border: "1px solid #35443D", borderRadius: 6, padding: "16px 16px 18px", marginBottom: 24 },
  areaNote: { margin: "0 0 12px", color: "#8B958B", fontSize: 12, fontStyle: "italic" },
  areaRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  areaPill: { fontFamily: "'Space Mono', monospace", fontSize: 11.5, letterSpacing: "0.02em", padding: "7px 14px", borderRadius: 999, border: "1.5px solid", cursor: "pointer", transition: "background 0.15s, color 0.15s" },
  officialBadge: { display: "inline-block", fontSize: 10, color: "#1C2622", padding: "4px 10px", borderRadius: 2, fontWeight: 700, marginBottom: 12 },
  dishListOfficial: { listStyle: "none", padding: 0, margin: "0 0 24px" },
  officialDish: { fontFamily: "'Fraunces', serif", fontSize: 24, fontWeight: 600, borderLeft: "3px solid", paddingLeft: 14, marginBottom: 10 },
  recHeader: { fontSize: 11, color: "#8B958B", marginBottom: 10 },
  dishList: { listStyle: "none", padding: 0, margin: 0 },
  recDish: { fontSize: 15, padding: "8px 0", borderBottom: "1px solid #2E3B34", color: "#D6CFBC" },
  navRow: { display: "flex", gap: 10, marginTop: 26, marginBottom: 0, paddingTop: 22, borderTop: "1px solid #35443D" },
  navBtn: { flex: 1, minWidth: 0, display: "flex", alignItems: "center", gap: 6, background: "#1C2622", border: "1.5px solid", borderRadius: 6, padding: "10px 12px", cursor: "pointer", fontFamily: "'Fraunces', serif", fontSize: 15 },
  navArrow: { fontSize: 18, flexShrink: 0, lineHeight: 1 },
  navLabel: { color: "#EDE6D6", flex: 1, textAlign: "left" },
  navHint: { margin: "0 0 20px", color: "#5E685F", fontSize: 12, fontStyle: "italic", textAlign: "center" },
  footer: { marginTop: 40, textAlign: "center", fontSize: 10, color: "#5E685F" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(10, 14, 12, 0.75)", display: "flex", alignItems: "flex-end", justifyContent: "center", padding: 0, zIndex: 100 },
  modalCard: { background: "#232F29", border: "1px solid #35443D", borderTopLeftRadius: 12, borderTopRightRadius: 12, padding: "28px 22px 24px", width: "100%", maxWidth: 720, maxHeight: "80vh", overflowY: "auto", position: "relative", boxShadow: "0 -8px 40px rgba(0,0,0,0.4)" },
  modalClose: { position: "absolute", top: 14, right: 16, background: "none", border: "none", color: "#8B958B", fontSize: 26, lineHeight: 1, cursor: "pointer", padding: 4 },
  modalTitle: { fontFamily: "'Fraunces', serif", fontSize: 26, fontWeight: 700, color: "#FFFFFF", margin: "0 0 18px", paddingRight: 30 },
  modalSectionLabel: { fontSize: 11, color: "#8B958B", marginBottom: 8, marginTop: 18 },
  modalBody: { fontSize: 15, lineHeight: 1.6, color: "#D6CFBC", margin: 0 },
  modalBodyMuted: { fontSize: 14, lineHeight: 1.6, color: "#5E685F", fontStyle: "italic", margin: 0 },
  modalChip: { background: "#1C262233", color: "#D6CFBC", border: "1px solid #35443D" },
  modalRecipeLink: { display: "block", textAlign: "center", marginTop: 24, padding: "12px 16px", borderRadius: 6, border: "1.5px solid #C97A3D", color: "#C97A3D", textDecoration: "none", fontSize: 14, fontWeight: 600 },
};
