export const styles = {
	page: {
		minHeight: "100vh",
		background: "#fefefe",
		color: "#2C2C2C",
		fontFamily: "'Work Sans', sans-serif",
	},
	titleHeader: {
		// marginBottom: 20,
		padding: 30,
		// textAlign: "center",
		background: "#ffffff",
		// borderTop: "3px solid #91b19d",
		// borderBottom: "3px solid #91b19d",
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	titleLogoRow: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 3,
	},
	logo: { width: 35 },
	titleLogoH1: {
		fontFamily: "'Rubik Dirt', cursive",
		fontSize: 18,
		fontWeight: 400,
		color: "#1A1A1A",
		margin: 0,
	},
	titleLogoH2: {
		fontFamily: "Nunito, sans-serif",
		fontSize: 12,
		fontWeight: 400,
		color: "#6B7280",
		margin: 0,
	},
	titleHeaderText: {
		display: "flex",
		flexDirection: "column",
		// alignItems: "flex-end",
		flex: 1,
	},
	nav: {
		display: "flex",
		alignItems: "center",
		gap: 24,
	},
	navLink: {
		fontFamily: "Nunito, sans-serif",
		fontSize: 12,
		fontWeight: 600,
		letterSpacing: "0.02em",
		textTransform: "uppercase",
	},
	eyebrowRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		gap: 12,
	},
	eyebrowRule: { width: 28, height: 1, background: "#91b19d", opacity: 0.4 },
	eyebrow: { fontSize: 10, color: "#91b19d", letterSpacing: "0.12em" },
	h1: {
		fontFamily: "'Fraunces', serif",
		fontWeight: 700,
		fontSize: "6vw",
		color: "#1A1A1A",
		margin: 0,
		textAlign: "start",
	},
	crumbTrail: {
		marginTop: 0,
		marginBottom: 16,
		display: "flex",
		flexDirection: "column",
		gap: 4,
		padding: "0 20px",
		// background: "#F0EBE3",
		// borderTop: "1px solid #E8E2D8",
		// borderBottom: "1px solid #E8E2D8",
	},
	titleBlock: { marginBottom: 20 },
	titleBlockRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 8,
	},
	overviewText: {
		fontSize: 14,
		lineHeight: 1.6,
		color: "#6B7280",
		margin: "10px 0 0",
	},
	crumbRow: {
		display: "flex",
		flexWrap: "wrap",
		alignItems: "baseline",
		gap: 6,
		paddingLeft: 4,
	},
	crumbPlain: { color: "#9CA3AF", fontSize: 10, margin: "6px 0 0" },
	crumbLink: {
		fontSize: 10,
		fontWeight: 600,
		color: "#4a7d5d",
		opacity: 0.55,
		cursor: "pointer",
		transition: "opacity 0.15s",
	},
	crumbSep: { fontSize: 12, color: "#4a7d5d" },
	crumbCountry: {
		fontFamily: "'Fraunces', serif",
		fontSize: 20,
		fontWeight: 700,
		color: "#1A1A1A",
	},
	foundedBadge: {
		display: "inline-block",
		fontSize: 11,
		padding: "5px 12px",
		borderRadius: 999,
		border: "1px solid",
		background: "#FFFFFF",
	},
	badgeRow: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 14 },
	sectionGrid: { display: "flex", flexDirection: "column", gap: 20 },
	sectionCard: {
		background: "#FFFFFF",
		// border: "1px solid #91b19d !important",
		padding: "20px 18px",
		// textAlign: "left",
		cursor: "pointer",
		color: "#2C2C2C",
		transition: "transform 0.15s",
		flex: 1,
		display: "flex",
		flexDirection: "column",
		gap: 8,
		// alignItems: "flex-start",
		// justifyContent: "flex-start",
		// boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
	},
	sectionCardRow: {
		display: "flex",
		flexDirection: "row",
		alignItems: "stretch",
		gap: 1,
		backgroundColor: "rgba(145, 177, 157, 0.4)",
	},
	sectionTag: { fontSize: 10, marginBottom: 8 },
	sectionNum: {
		fontSize: 12,
		fontFamily: "'Rubik Dirt', cursive",
		lineHeight: 2,
		color: "#91b19d",
		textDecoration: "underline",
	},
	sectionName: {
		fontFamily: "'Cinzel', serif",
		fontSize: 28,
		fontWeight: 300,
		color: "#1A1A1A",
		// marginBottom: 6,
	},
	sectionDesc: { fontFamily: "Nunito, sans-serif", fontSize: 13, color: "#6B7280", lineHeight: 1.5 },
	comingSoonBox: {
		border: "1px solid",
		borderRadius: 6,
		padding: "40px 24px",
		textAlign: "center",
		marginTop: 8,
	},
	spiceListCount: {
		fontSize: 11,
		color: "#9CA3AF",
		fontFamily: "'Space Mono', monospace",
	},
	comingSoonDesc: {
		fontSize: 14,
		color: "#6B7280",
		lineHeight: 1.6,
		maxWidth: 420,
		margin: "0 auto",
	},
	regionGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
	spiceLetterGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(5, 1fr)",
		gap: 10,
	},
	regionCard: {
		background: "#FFFFFF",
		border: "1px solid",
		borderRadius: 4,
		padding: "18px 16px",
		textAlign: "left",
		cursor: "pointer",
		color: "#2C2C2C",
		transition: "transform 0.15s",
		boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
	},
	spiceLetterCard: {
		background: "#FFFFFF",
		border: "1px solid",
		borderRadius: 4,
		padding: "14px 8px",
		textAlign: "center",
		cursor: "pointer",
		color: "#2C2C2C",
		transition: "transform 0.15s",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
	},
	regionTag: { fontSize: 10, marginBottom: 8 },
	regionName: {
		fontFamily: "'Fraunces', serif",
		fontSize: 19,
		fontWeight: 600,
		marginBottom: 4,
	},
	regionCount: { fontSize: 12, color: "#9CA3AF" },
	groupCount: {
		fontSize: 11,
		color: "#9CA3AF",
		marginTop: 4,
		fontFamily: "'Work Sans', sans-serif",
	},
	countryGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
	countryCard: {
		background: "#FFFFFF",
		border: "1px solid",
		borderRadius: 4,
		padding: "14px 14px",
		textAlign: "left",
		cursor: "pointer",
		color: "#1A1A1A",
		fontFamily: "'Fraunces', serif",
		fontSize: 16,
		transition: "transform 0.15s",
		boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
	},
	detail: {
		background: "#FFFFFF",
		borderTop: "3px solid #91b19d",
		padding: "12px 20px 20px",
		width: "100vw",
		marginLeft: "-20px",
	},
	areaBox: {
		background: "#FFFFFF",
		border: "1px solid #E8E2D8",
		borderRadius: 8,
		padding: "18px 18px 20px",
		marginBottom: 28,
	},
	areaNote: {
		margin: "0 0 14px",
		color: "#9CA3AF",
		fontSize: 12,
		fontStyle: "italic",
	},
	areaRow: { display: "flex", flexWrap: "wrap", gap: 8 },
	areaPill: {
		fontFamily: "'Space Mono', monospace",
		fontSize: 11.5,
		letterSpacing: "0.02em",
		padding: "7px 14px",
		borderRadius: 999,
		border: "1px solid",
		cursor: "pointer",
		transition: "background 0.15s, color 0.15s",
	},
	officialBadge: {
		display: "inline-block",
		fontSize: 10,
		color: "#FFFFFF",
		padding: "4px 10px",
		borderRadius: 2,
		fontWeight: 700,
		marginBottom: 16,
	},
	dishListOfficial: { listStyle: "none", padding: 0, margin: "0 0 28px" },
	officialDish: {
		fontFamily: "'Fraunces', serif",
		fontSize: 26,
		fontWeight: 600,
		borderLeft: "3px solid",
		paddingLeft: 16,
		marginBottom: 12,
		color: "#1A1A1A",
	},
	recHeader: { fontSize: 10, color: "#9CA3AF", marginBottom: 12 },
	dishList: { listStyle: "none", padding: 0, margin: 0 },
	recDish: {
		fontSize: 15,
		padding: "11px 0",
		borderBottom: "1px solid #EDE8DF",
		color: "#3D3D3D",
	},
	navRow: {
		display: "flex",
		gap: 8,
		marginBottom: 20,
		justifyContent: "flex-end",
	},
	navBtn: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		background: "#FFFFFF",
		border: "1px solid #91b19d",
		borderRadius: 6,
		width: 36,
		height: 36,
		cursor: "pointer",
		flexShrink: 0,
	},
	navArrow: { color: "#91b19d", fontSize: 18, flexShrink: 0, lineHeight: 1 },
	navLabel: { color: "#2C2C2C", flex: 1, textAlign: "left" },
	navHint: {
		margin: "0 0 20px",
		color: "#B0A89E",
		fontSize: 12,
		fontStyle: "italic",
		textAlign: "center",
	},
	footer: {
		marginTop: 40,
		textAlign: "center",
		fontSize: 10,
		color: "#B0A89E",
	},
	modalOverlay: {
		position: "fixed",
		inset: 0,
		background: "rgba(20, 15, 10, 0.5)",
		display: "flex",
		alignItems: "flex-end",
		justifyContent: "center",
		padding: 0,
		zIndex: 100,
	},
	modalCard: {
		background: "#FFFFFF",
		border: "1px solid #E8E2D8",
		borderTopLeftRadius: 12,
		borderTopRightRadius: 12,
		padding: "28px 22px 24px",
		width: "100%",
		maxWidth: 720,
		maxHeight: "80vh",
		overflowY: "auto",
		position: "relative",
		boxShadow: "0 -4px 24px rgba(0,0,0,0.12)",
	},
	modalClose: {
		position: "absolute",
		top: 14,
		right: 16,
		background: "none",
		border: "none",
		color: "#9CA3AF",
		fontSize: 26,
		lineHeight: 1,
		cursor: "pointer",
		padding: 4,
	},
	modalTitle: {
		fontFamily: "'Fraunces', serif",
		fontSize: 26,
		fontWeight: 700,
		color: "#1A1A1A",
		margin: "0 0 18px",
		paddingRight: 30,
	},
	modalSectionLabel: {
		fontSize: 11,
		color: "#9CA3AF",
		marginBottom: 8,
		marginTop: 18,
	},
	modalBody: { fontSize: 15, lineHeight: 1.6, color: "#4B4B4B", margin: 0 },
	modalBodyMuted: {
		fontSize: 14,
		lineHeight: 1.6,
		color: "#B0A89E",
		fontStyle: "italic",
		margin: 0,
	},
	modalChip: {
		background: "#F8F5F0",
		color: "#4B4B4B",
		border: "1px solid #E8E2D8",
	},
	modalRecipeLink: {
		display: "block",
		textAlign: "center",
		marginTop: 24,
		padding: "12px 16px",
		borderRadius: 6,
		border: "1px solid #C97A3D",
		color: "#C97A3D",
		textDecoration: "none",
		fontSize: 14,
		fontWeight: 600,
	},
};
